### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anrom7** [romanyshyn-natalia/Course_Homeworks#1]
Тема: Розпізнавання іменованих сутностей в медичних текстах?
Мова: англійська?
Дані: електронні медичні карточки?
Колись давно ми вже маркували NE для медичних тестів українською мовою https://github.com/anrom7/NERU_corpus

**Comment by romanyshyn-natalia** [comment]
Тема: Обробка та класифікація медичних записів.
Мова: так, англійська.
Дані: електронні медичні записи.
